server:
  port: 8760
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  application:
    name: config-module

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html